### ISSUE TITLE
Cancel a started download

### ISSUE THREAD

**Issue by marcodecarolisidt** [Baseflow/flutter_cache_manager#309] opened 2021-04-29 13:40 UTC
## 🚀 Feature Requests

When we start a very big download with 
```
DefaultCacheManager().downloadFile(url)
``` 
I would like to give the possibility to the user to cancel the download

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by renefloor** [comment] 2021-04-30 10:15
Thanks for the feature request. It is a duplicate of #208
Please at a 👍 to the original post in that issue.

**Closed as completed by renefloor** 2021-04-30 10:15 UTC
