### ISSUE TITLE
Change to pure dart DB so it works on Web, Mobile and Desktop automatically

### ISSUE THREAD

**Issue by joe-getcouragenow** [Baseflow/flutter_cache_manager#217] opened 2020-09-01 14:20 UTC
## 🐛 Bug Report

https://pub.dev/packages/hive_cache

This is much faster than SQL and runs on Web, Mobile and desktop with code changes.

We have been using in Production and many other also.

Here is the benchmark comparing HIVE to SQLite: https://pub.dev/packages/hive#benchmark

**Comment by renefloor** [comment] 2020-09-01 14:24
Duplicate of #121 
We are working on supporting more types of databases.

**Closed by renefloor** 2020-09-01 14:24 UTC
